# Generated by Django 5.2.7 on 2025-10-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100, unique=True)),
                ('n_estacionamientos_totales', models.PositiveIntegerField()),
                ('disponibles', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20)),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('apellido_conductor', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_conductor', models.CharField(blank=True, max_length=12, null=True)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('zona_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='estacionamientos.zonaestacionamiento')),
            ],
        ),
    ]
