# Generated by Django 5.2.7 on 2025-10-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_administrativodebil_guardia_administrativofuerte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativodebil',
            options={'verbose_name': 'Administrativo débil', 'verbose_name_plural': 'Administrativos débiles'},
        ),
        migrations.AlterModelOptions(
            name='administrativofuerte',
            options={'verbose_name': 'Administrativo fuerte', 'verbose_name_plural': 'Administrativos fuertes'},
        ),
        migrations.AlterModelOptions(
            name='guardia',
            options={'verbose_name': 'Guardia', 'verbose_name_plural': 'Guardias'},
        ),
    ]
